---
galaxy_info:
  author: Ruchitha Gowda
  description: Role to install Nginx
  license: MIT
  min_ansible_version: 2.15
  platforms:
    - name: Ubuntu
      versions:
        - all
  categories:
    - web
dependencies: []
